version: "3"
services:
  game-frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - REACT_APP_HOST=//humanwelfare.uwaterloo.ca:8080
