version: '3'

services:
  node-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node_network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node_network

volumes:
  dbdata:

networks:
  node_network:
